---
title: "Problem 2"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
theme: cerulean
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```

```{r import, include=FALSE}
data(ny_noaa)

ny_noaa=ny_noaa
```

```{r tidy, include=FALSE}
smaller_noaa <- ny_noaa %>% 
  janitor::clean_names() %>%
  separate(date, into=c("year", "month", "day"), sep= "-") %>%
  filter(year>=2000 & year<=2004) %>% 
  mutate(tmax = as.numeric(tmax)/10,
         tmin = as.numeric(tmin)/10,
        prcp = as.numeric(prcp)/10,
        snow_mm=snow, 
        month= as.numeric(month),
        snwd=round(snow_mm*0.03937*4)/4) %>% 
  mutate(month = month.name[month]) %>% 
  drop_na(prcp, snow_mm, tmax, tmin) %>% 
  select(-snwd)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Boxplot of precipitation (mm) in year 2000

```{r}
smaller_noaa %>% 
  filter(year==2000) %>%
  mutate(month = factor(month, levels=month.name)) %>%
  plot_ly(y = ~prcp, color = ~month, type = "box", colors = "viridis")
```

Column {data-width=350}
-----------------------------------------------------------------------
### Barchart of mean minimum temperature (C) by month (2000-2004) 

```{r}
smaller_noaa %>% 
  group_by(month) %>% 
  summarize(mean_tmin= mean(tmin, na.rm= TRUE)) %>% 
  drop_na(mean_tmin) %>% 
  mutate(month = factor(month, levels=month.name)) %>%
  plot_ly(x = ~month, y = ~mean_tmin, color = ~month, type = "bar", colors = "viridis")
```

### Scatterplot of maximum temperature (C) and snowfall (mm) by year(2000-2004)

```{r}
smaller_noaa %>%
  plot_ly(
    x = ~tmax, y = ~snow_mm, type = "scatter", mode = "markers", alpha = 0.5, color=~year)
```

`rmarkdown::render("plotly.Rmd", output_format = "flexdashboard::flex_dashboard")`