---
title: "problem2"
author: "Ayako Sekiya"
date: "2022-10-25"
output: html_document
---

```{r libraries}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

```{r import}
data(ny_noaa)

ny_noaa=ny_noaa
```

I will first tidy the data set. It is important to standardize some of the values including, `snow`, `tmax`, `tmin`, and `prcp`.

```{r tidy}
ny_noaa <- ny_noaa %>% 
  janitor::clean_names() %>%
  separate(date, into=c("year", "month", "day"), sep= "-") %>% 
  mutate(tmax = as.numeric(tmax)/10,
         tmin = as.numeric(tmin)/10,
        prcp = as.numeric(prcp)/10, 
        snow_mm=snow, 
        snow=round(snow_mm*0.03937*4)/4) %>% 
  drop_na() %>% 
select(-snow)
```

## Scatterplot

I will first create a scatterplot for one of my plots for the flexdashboard. 

```{r scatterplot}
scatter_ggplot = 
  ny_noaa %>%
  ggplot(aes(x = year, y = tmin)) +
  geom_point(alpha = 0.25) +
  coord_cartesian()

ggplotly(scatter_ggplot)
```

## Boxplot

I will create a boxplot for one of my plots for the flexdashboard. 

```{r boxplot}
box_ggplot = 
  ny_noaa %>% 
  ggplot(aes(x = year, y = snow_mm, fill = year)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplotly(box_ggplot)
```

## Bar chart

I will create a barchart for one of my plots for the flexdashboard. 

```{r bar chart}
bar_ggplot = 
  ny_noaa %>% 
  ggplot(aes(x = year, y = snow_mm, fill = year)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplotly(bar_ggplot)
```
