---
title: "Resume"
output: html_document
---
# Ayako Sekiya 
New York, NY | as6445@cumc.columbia.edu | https://www.linkedin.com/in/ayako-s-908316157/ 

## Education
**Columbia University, Mailman School of Public Health**, New York, NY 	
Expected May 2023
Master of Public Health, Epidemiology; Certificate: Applied Biostatistics and Public Health Data Science
Relevant Courses: Applied Regression I & II |Applications of Epidemiologic Research Methods | Data Science I 

**University of Maryland-College Park**, College Park, MD 	
August 2017-December 2020
Bachelor of Science, Public Health Science; Sustainability Studies Minor
Honors: Magna Cum Laude, Honors Humanities Program, Phi Alpha Epsilon Honorary Society

## Research Experiences
**Summer Research Intern**
May 2022-August 2022
National Institutes of Health (NIH), National Cancer Institute (NCI), Bethesda, MD

*	Developed methods to understand age, period, and cohort effects of kidney cancer incidence in the United States to decipher recent changes in trends among different demographics with mentors. 
*	Managed independent descriptive epidemiology analysis in SEER*Stat, JoinPoint Regression Program, and R to understand kidney cancer incidence among young adults. 
*	Collaborated with biostatisticians to visualize trends in R and tested significance using statistical tests. 
*	Designed poster including findings from quantitative analyses and presented at institute and branch-wide events to disseminate findings and help guide future publications. 

**Clinical Research Intern**
May 2021-August 2021
Multidisciplinary Association for Psychedelic Studies Public Beneficiary Corporation, San Jose, CA

*	Analyzed two clinical trial data sets using SAS and presented findings to team to showcase treatment patterns and compare clinical outcomes between placebo and treatment groups.
*	Inspected academic literature and clinical trial data on the usage of MDMA in psychotherapy among PTSD patients and summarized findings to aid in designing future clinical trials on psychotherapy. 
*	Updated four clinical trial protocols by creating charts and trackers for data changes to increase efficiency and accuracy in the editing process and ensure compliance with NIH guidelines.

## Leadership Experience
**Graduate Teaching Assistant** 	
September 2022-Present
Columbia University, Mailman School of Public Health, New York, NY

*	Facilitate weekly lab sections for 20 students to further students’ understanding and mastery of Quantitative Foundations of the Research Methods and Applications studio and STATA.
*	Collaborate with 25 TAs and 2 Professors to review and provide feedback on assignments in a timely manner.
*	Oversaw weekly office hours to provide customized assistance to meet individual learning styles. 

## Skills
MS Office: Word, Excel, PowerPoint (Advanced); SAS (Advanced); R (Advanced); STATA (Intermediate)
